#!/bin/sh

REPOS="$1"
REV="$2"

# /usr/local/apache-php5/php5/bin/php /home/projects.ez.no/www5upgraded/ezpublish-4.4.0/extension/ezprojects/bin/php/post-commit.php "$REPOS" "$REV"
/usr/bin/php /home/projects.ez.no/www5upgraded/ezpublish-4.4.0/extension/ezprojects/bin/php/post-commit.php "$REPOS" "$REV"
